first pass add support for staging releases

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -45,6 +45,7 @@ PREFIX=$(git config --get gitflow.prefix.release)
 usage() {
 	echo "usage: git flow release [list] [-v]"
 	echo "       git flow release start [-F] <version>"
+        echo "       git flow release stage <version>"
 	echo "       git flow release finish [-Fsumpk] <version>"
 	echo "       git flow release publish <name>"
 	echo "       git flow release track <name>"
@@ -185,12 +186,63 @@ cmd_start() {
 	echo
 }
 
+
+cmd_stage() {
+        parse_args "$@"
+        require_version_arg
+        require_branch "$BRANCH"
+        require_clean_working_tree
+        git fetch -q "$ORIGIN" "$STAGING_BRANCH" || die "Could not fetch $STAGING_BRANCH from $ORIGIN."
+
+        # sanity check staging branch is up to date
+	if has "$ORIGIN/$STAGING_BRANCH" "$(git_remote_branches)"; then
+		require_branches_equal "$STAGING_BRANCH" "$ORIGIN/$STAGING_BRANCH"
+	fi
+
+	# try to merge into staging
+	# in case a previous attempt to stage this release branch has failed,
+	# but the merge into staging was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$STAGING_BRANCH"; then
+		git checkout "$STAGING_BRANCH" || \
+		  die "Could not check out $STAGING_BRANCH."
+		git merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+        
+        # try to merge into develop
+	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+		git checkout "$DEVELOP_BRANCH" || \
+		  die "Could not check out $DEVELOP_BRANCH."
+
+		# TODO: Actually, accounting for 'git describe' pays, so we should
+		# ideally git merge --no-ff $tagname here, instead!
+		git merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+
+        git push "$ORIGIN" "$STAGING_BRANCH" || \
+		die "Could not push to $STAGING_BRANCH from $ORIGIN."
+	git push "$ORIGIN" "$DEVELOP_BRANCH" || \
+		die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+	git push "$ORIGIN" :"$BRANCH" || \
+		die "Could not delete the remote $BRANCH in $ORIGIN."
+	echo
+	echo "Summary of actions:"
+	echo "- Latest objects have been fetched from '$ORIGIN'"
+	echo "- Release branch has been merged into '$STAGING_BRANCH'"
+	echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
+	echo "- '$DEVELOP_BRANCH', '$STAGING_BRANCH' and tags have been pushed to '$ORIGIN'"
+	echo
+
+
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
 
@@ -217,6 +269,11 @@ cmd_finish() {
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
+
+        # ensure the release branch was already merged into staging
+        git_is_branch_merged_into "$BRANCH" "$STAGING_BRANCH" || \
+            die "The release branch $BRANCH has not been merged into $STAGING_BRANCH"
+
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
