add some safties for finish action and staging branch

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -196,6 +196,7 @@ cmd_stage() {
         require_branch "$BRANCH"
         require_clean_working_tree        
         git fetch -q "$ORIGIN" "$STAGING_BRANCH" || die "Could not fetch $STAGING_BRANCH from $ORIGIN."
+        git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
         
 	# try to merge into staging
 	# in case a previous attempt to stage this release branch has failed,
@@ -258,11 +259,16 @@ cmd_finish() {
 	if flag fetch; then
 		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
 		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git fetch -q "$ORIGIN" "$STAGING_BRANCH" || \
+		  die "Could not fetch $STAGING_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
 	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	fi
+	if has "$ORIGIN/$STAGING_BRANCH" "$(git_remote_branches)"; then
+		require_branches_equal "$STAGING_BRANCH" "$ORIGIN/$STAGING_BRANCH"
 	fi
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -308,6 +314,19 @@ cmd_finish() {
 		  # TODO: What do we do now?
 	fi
 
+        # ensure we also merged into staging
+	if ! git_is_branch_merged_into "$BRANCH" "$STAGING_BRANCH"; then
+		git checkout "$STAGING_BRANCH" || \
+		  die "Could not check out $STAGING_BRANCH."
+
+		# TODO: Actually, accounting for 'git describe' pays, so we should
+		# ideally git merge --no-ff $tagname here, instead!
+		git merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+        
+
 	# delete branch
 	if noflag keep; then
 		git branch -d "$BRANCH"
@@ -316,6 +335,8 @@ cmd_finish() {
 	if flag push; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$STAGING_BRANCH" || \
+			die "Could not push to $STAGING_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
@@ -338,7 +359,7 @@ cmd_finish() {
 		echo "- Hotfix branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$DEVELOP_BRANCH', '$STAGING_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo
 }
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -258,11 +258,16 @@ cmd_finish() {
 	if flag fetch; then
 		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
 		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git fetch -q "$ORIGIN" "$STAGING_BRANCH" || \
+		  die "Could not fetch $STAGING_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
 	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	fi
+	if has "$ORIGIN/$STAGING_BRANCH" "$(git_remote_branches)"; then
+		require_branches_equal "$STAGING_BRANCH" "$ORIGIN/$STAGING_BRANCH"
 	fi
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -313,9 +318,23 @@ cmd_finish() {
 		  # TODO: What do we do now?
 	fi
 
+        # and staging
+	if ! git_is_branch_merged_into "$BRANCH" "$STAGING_BRANCH"; then
+		git checkout "$STAGING_BRANCH" || \
+		  die "Could not check out $STAGING_BRANCH."
+
+		# TODO: Actually, accounting for 'git describe' pays, so we should
+		# ideally git merge --no-ff $tagname here, instead!
+		git merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+
 	if flag push; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$STAGING_BRANCH" || \
+			die "Could not push to $STAGING_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
@@ -350,7 +369,7 @@ cmd_finish() {
 		echo "- Release branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$DEVELOP_BRANCH', '$STAGING_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
 	fi
 	echo
